<?php
namespace app\admin\controller;
use app\admin\controller\Base;
use app\admin\model\DContr;
use think\Request;

class Contr extends Base{

    protected $model;
    protected $request;
    protected $param;

    protected $beforeActionList = [
        'permission' => ['except' => 'login,getlist']
    ];

    protected function permission(){
        parent::permission(); // TODO: Change the autogenerated stub
        $this->param = $this->request->param();
        $this->model = new DContr($this->ad_uid);
    }

    public function dev(){
      try {
        $res = $this->model->Dev();
        return json_encode(['code' => 200, 'msg' => 'success']);
      } catch (\Exception $e) {
        return json_encode(['code' => $e->getCode(), 'msg' => $e->getMessage()]);
      }
    }

    public function devList($page = 0, $length = 10){
        $this->view->engine->layout(false);
        $list = $this->model->getList($page, $length);
        $this->assign('list', $list);
        return $this->fetch();
    }

    public function devAdd(){
        $this->view->engine->layout(false);
        return $this->fetch();
    }

    public function devEdit(){
        $this->view->engine->layout(false);
        return $this->fetch();
    }

    public function devDel(){
        $this->view->engine->layout(false);
        return $this->fetch();
    }
    
}
